### ISSUE TITLE
В кондиционере нет функции выключения

### ISSUE THREAD

**Issue by tayanov** [dmitry-k/yandex_smart_home#11]
В списке голосовых команд не нашел команды выключить кондиционер. На пробу Алиса ответила что пока не умеет) остальное работает

**Comment by ginkage** [comment]
При попытке включать/выключать кондиционер я получаю такое:

```
2019-06-06 19:11:11 ERROR (MainThread) [custom_components.yandex_smart_home.smart_home] Unexpected error
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/smart_home.py", line 48, in _process
    result = await handler(hass, data, message)
  File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/smart_home.py", line 178, in handle_devices_execute
    capability.get('state', {}))
  File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/helpers.py", line 175, in execute
    await cpb.set_state(data, state)
  File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/capability.py", line 160, in set_state
    }, blocking=True, context=data.context)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/core.py", line 1150, in async_call
    self._execute_service(handler, service_call))
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/core.py", line 1172, in _execute_service
    await handler.func(service_call)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_component.py", line 194, in handle_service
    required_features
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/service.py", line 316, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/service.py", line 337, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/climate/__init__.py", line 480, in turn_on
    raise NotImplementedError()
NotImplementedError
2019-06-06 19:11:11 ERROR (MainThread) [custom_components.yandex_smart_home.smart_home] Error handling message {'payload': {'devices': [{'id': 'climate.living_room_hvac', 'capabilities': [{'state': {'value': True, 'instance': 'on'}, 'type': 'devices.capabilities.on_off'}]}]}}: {'error_code': 'INTERNAL_ERROR'}
```

Кондиционер управляется платформой MQTT, кстати. Не уверен, есть ли там поддержка on_off (там для этого просто используется режим "off").
