### ISSUE TITLE
не работает mute/unmute

### ISSUE THREAD

**Issue by Filecast** [dmitry-k/yandex_smart_home#12]
Привет не работает mute/unmute на телеке
В логе ha:
2019-06-06 17:18:47 ERROR (MainThread) [custom_components.yandex_smart_home.smart_home] Unexpected error
Traceback (most recent call last):
File "/home/den/.homeassistant/custom_components/yandex_smart_home/smart_home.py", line 48, in _process
result = await handler(hass, data, message)
File "/home/den/.homeassistant/custom_components/yandex_smart_home/smart_home.py", line 178, in handle_devices_execute
capability.get('state', {}))
File "/home/den/.homeassistant/custom_components/yandex_smart_home/helpers.py", line 174, in execute
if type == cpb.type and state['instance'] == cpb.instance:
TypeError: 'NoneType' object is not subscriptable
2019-06-06 17:18:47 ERROR (MainThread) [custom_components.yandex_smart_home.smart_home] Error handling message {'payload': {'devices': [{'id': 'media_player.lg_tv', 'capabilities': [{'type': 'devices.capabilities.toggle', 'state': None}]}, {'id': 'media_player.living_room_tv', 'capabilities': [{'type': 'devices.capabilities.toggle', 'state': None}]}]}}: {'error_code': 'INTERNAL_ERROR'}
2019-06-06 17:19:01 ERROR (MainThread) [custom_components.yandex_smart_home.smart_home] Unexpected error
Traceback (most recent call last):
File "/home/den/.homeassistant/custom_components/yandex_smart_home/smart_home.py", line 48, in _process
result = await handler(hass, data, message)
File "/home/den/.homeassistant/custom_components/yandex_smart_home/smart_home.py", line 178, in handle_devices_execute
capability.get('state', {}))
File "/home/den/.homeassistant/custom_components/yandex_smart_home/helpers.py", line 174, in execute
if type == cpb.type and state['instance'] == cpb.instance:
TypeError: 'NoneType' object is not subscriptable
2019-06-06 17:19:01 ERROR (MainThread) [custom_components.yandex_smart_home.smart_home] Error handling message {'payload': {'devices': [{'id': 'media_player.lg_tv', 'capabilities': [{'type': 'devices.capabilities.toggle', 'state': None}]}, {'id': 'media_player.living_room_tv', 'capabilities': [{'type': 'devices.capabilities.toggle', 'state': None}]}]}}: {'error_code': 'INTERNAL_ERROR'}

**Comment by Filecast** [comment]
Проблема не временная! Причём вылетает такое... когда говоришь Алисе «выключи звук на телевизоре», кнопками все в яндексе выключает и включает. Есть подозрение что такое ища двух тв с одинаковыми именами но в разных комнатах.

**Comment by dmitry-k** [comment]
Я как-то даже не пробовал голосом включать-выключать звук, проверю дома. Но очень похоже на баг яндекса.

**Comment by dmitry-k** [comment]
У меня тоже самое. Это явно баг яндекса. Возможно попозже напишу им.

У них похоже вообще проблемы с телевизором/медиаплеером. Там и громкость с кнопок работает, а на голосовые команды Алиса отвечает "не получилось" (потому пока и не добавил это).

**Comment by dmitry-k** [comment]
Яндекс исправили это в одном из обновлений похоже.
