### ISSUE TITLE
Алиса не может уменьшить/увеличить яркость

### ISSUE THREAD

**Issue by nick2525** [dmitry-k/yandex_smart_home#127]
@dmitry-k Используется группа лампочек, в которой есть light switch. При этом, команда сделай яркость 20% работает. Лампы в группе yeelight Если использовать группу ламп без light switch, то все работает. Видимо, Алисе не хватает данных насколько уменьшать яркость, что очень странно, так как сделай яркость 20% работает.

**Comment by lexural** [comment]
У меня Алиса также себя ведёт с диммерами ТУЯ.

**Comment by dmitry-k** [comment]
Чтобы попытаться найти причину нужны логи запросов от яндекса(можно включить debug логирование для компонента в HA или использовать тестовую консоль в яндексе) и желательно название интеграций

**Comment by nick2525** [comment]
@dmitry-k 
Ошибка такая

Error handling message {'payload': {'devices': [{'id': 'light.chi_lights', 'capabilities': [{'type': 'devices.capabilities.range', 'state': {'instance': 'brightness', 'relative': True, 'value': -20}}]}]}}: {'error_code': 'INTERNAL_ERROR'} 

Traceback (most recent call last):
  File "/root/.homeassistant/custom_components/yandex_smart_home/smart_home.py", line 46, in _process
    result = await handler(hass, data, message)
  File "/root/.homeassistant/custom_components/yandex_smart_home/smart_home.py", line 152, in handle_devices_execute
    await entities[entity_id].execute(data,
  File "/root/.homeassistant/custom_components/yandex_smart_home/helpers.py", line 224, in execute
    await cpb.set_state(data, state)
  File "/root/.homeassistant/custom_components/yandex_smart_home/capability.py", line 1001, in set_state
    await self.hass.services.async_call(
  File "/home/nick252/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1399, in async_call
    processed_data = handler.schema(service_data)
  File "/home/nick252/homeassistant/lib/python3.9/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/home/nick252/homeassistant/lib/python3.9/site-packages/voluptuous/validators.py", line 341, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/home/nick252/homeassistant/lib/python3.9/site-packages/voluptuous/validators.py", line 337, in _exec
    v = func(v)
  File "/home/nick252/homeassistant/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/home/nick252/homeassistant/lib/python3.9/site-packages/voluptuous/validators.py", line 215, in _run
    return self._exec(self._compiled, value, path)
  File "/home/nick252/homeassistant/lib/python3.9/site-packages/voluptuous/validators.py", line 341, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/home/nick252/homeassistant/lib/python3.9/site-packages/voluptuous/validators.py", line 339, in _exec
    v = func(path, v)
  File "/home/nick252/homeassistant/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/home/nick252/homeassistant/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/home/nick252/homeassistant/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/home/nick252/homeassistant/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: value must be at least 0 for dictionary value @ data['brightness_pct']

========================================================================
Используется интеграция light group
light 4:
  - platform: group
    name: chi_lights
    entities:
      - light.yee8
      - light.yee10
      - light.yee12
      - light.chiinter
В них лампы с интеграции yeelight и light.chiinter это light switch
light 101:
  - platform: switch
    name: chiinter
    entity_id: switch.chi

**Comment by lexural** [comment]
Выловил. Сказал Алисе "Убавь яркость на 10%"

```
2021-01-24 22:59:13 ERROR (MainThread) [custom_components.yandex_smart_home.smart_home] Unexpected error
Traceback (most recent call last):
File "/config/custom_components/yandex_smart_home/smart_home.py", line 46, in _process
result = await handler(hass, data, message)
File "/config/custom_components/yandex_smart_home/smart_home.py", line 152, in handle_devices_execute
await entities[entity_id].execute(data,
File "/config/custom_components/yandex_smart_home/helpers.py", line 224, in execute
await cpb.set_state(data, state)
File "/config/custom_components/yandex_smart_home/capability.py", line 1001, in set_state
await self.hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1399, in async_call
processed_data = handler.schema(service_data)
File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__
return self._exec((Schema(val) for val in self.validators), v)
File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec
raise e if self.msg is None else AllInvalid(self.msg, path=path)
File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec
v = func(v)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
return self._compiled([], data)
File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 215, in _run
return self._exec(self._compiled, value, path)
File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec
raise e if self.msg is None else AllInvalid(self.msg, path=path)
File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 339, in _exec
v = func(path, v)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
return schema(data)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
return self._compiled([], data)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
return base_validate(path, iteritems(data), out)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: value must be at least 0 for dictionary value @ data['brightness_pct']
2021-01-24 22:59:13 ERROR (MainThread) [custom_components.yandex_smart_home.smart_home] Error handling message {'payload': {'devices': [{'id': 'light.0x60a423fffe3e65fe', 'capabilities': [{'type': 'devices.capabilities.range', 'state': {'instance': 'brightness', 'relative': True, 'value': -10}}]}, {'id': 'light.0xbc33acfffe5ac430', 'capabilities': [{'type': 'devices.capabilities.range', 'state': {'instance': 'brightness', 'relative': True, 'value': -10}}]}]}}: {'error_code': 'INTERNAL_ERROR'}
```

**Comment by nick2525** [comment]
Похоже, Алиса не умеет сделать минус 20% от 100%, но сделать 80% она умеет

**Comment by lexural** [comment]
> Похоже, Алиса не умеет сделать минус 20% от 100%, но сделать 80% она умеет

Либо не получает текущею яркость, думая что ноль. И вычитает из нуля. У меня и не прибавляет тоже. Тупо выставляет например 20% если просишь её повысить на 20%

**Comment by lexural** [comment]
Вообщем решил вроде. У меня работает.

в файле capability.py

Ищем 
```
        await self.hass.services.async_call(
            light.DOMAIN,
            light.SERVICE_TURN_ON, {
                ATTR_ENTITY_ID: self.state.entity_id,
                light.ATTR_BRIGHTNESS_PCT: state['value']
            }, blocking=True, context=data.context)
```

и заменяем на:

```
        if ('relative' in state and state['relative'] == True):
            await self.hass.services.async_call(
                light.DOMAIN,
                light.SERVICE_TURN_ON, {
                    ATTR_ENTITY_ID: self.state.entity_id,
                    light.ATTR_BRIGHTNESS_STEP_PCT: state['value']
                }, blocking=True, context=data.context)
        else:
            await self.hass.services.async_call(
                light.DOMAIN,
                light.SERVICE_TURN_ON, {
                    ATTR_ENTITY_ID: self.state.entity_id,
                    light.ATTR_BRIGHTNESS_PCT: state['value']
                }, blocking=True, context=data.context)
```

Перезагружаем HA

**Comment by nick2525** [comment]
Пофикшено, можно закрывать
