### ISSUE TITLE
Множество SmartHomeError: Invalid value при старте HA после обновления до a89bf74d16e3b68e8040db9415e6b925292f4eb3

### ISSUE THREAD

**Issue by PaulAnnekov** [dmitry-k/yandex_smart_home#177]
@glebsterx 

После обновления до a89bf74d16e3b68e8040db9415e6b925292f4eb3 я настроил нотификатор и при старте HA начал получать кучу ошибок такого вида:

```
...
2021-04-18 14:46:55 INFO (MainThread) [custom_components.yandex_smart_home.notifier] Update group.decorative_lighting: off
...
2021-04-18 14:46:56 INFO (MainThread) [custom_components.yandex_smart_home.notifier] Update switch.switch_3: on
2021-04-18 14:46:56 INFO (MainThread) [custom_components.yandex_smart_home.notifier] Update switch.hall_light: off
2021-04-18 14:46:56 INFO (MainThread) [custom_components.yandex_smart_home.notifier] Update cover.curtain_motor_level: open
...
2021-04-18 14:47:27 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 37, in listener
    await notifier.async_event_handler(event)
  File "/config/custom_components/yandex_smart_home/notifier.py", line 115, in async_event_handler
    device = entity.query_serialize()
  File "/config/custom_components/yandex_smart_home/helpers.py", line 221, in query_serialize
    properties.append(ppt.get_state())
  File "/config/custom_components/yandex_smart_home/prop.py", line 94, in get_state
    'value': self.get_value()
  File "/config/custom_components/yandex_smart_home/prop.py", line 157, in get_value
    raise SmartHomeError(ERR_NOT_SUPPORTED_IN_CURRENT_MODE, "Invalid value")
custom_components.yandex_smart_home.error.SmartHomeError: Invalid value
2021-04-18 14:47:27 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 37, in listener
    await notifier.async_event_handler(event)
  File "/config/custom_components/yandex_smart_home/notifier.py", line 115, in async_event_handler
    device = entity.query_serialize()
  File "/config/custom_components/yandex_smart_home/helpers.py", line 221, in query_serialize
    properties.append(ppt.get_state())
  File "/config/custom_components/yandex_smart_home/prop.py", line 94, in get_state
    'value': self.get_value()
  File "/config/custom_components/yandex_smart_home/prop.py", line 190, in get_value
    raise SmartHomeError(ERR_NOT_SUPPORTED_IN_CURRENT_MODE, "Invalid value")
custom_components.yandex_smart_home.error.SmartHomeError: Invalid value
2021-04-18 14:47:27 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 37, in listener
    await notifier.async_event_handler(event)
  File "/config/custom_components/yandex_smart_home/notifier.py", line 116, in async_event_handler
    if old_entity.query_serialize() != device: # есть изменения
  File "/config/custom_components/yandex_smart_home/helpers.py", line 221, in query_serialize
    properties.append(ppt.get_state())
  File "/config/custom_components/yandex_smart_home/prop.py", line 94, in get_state
    'value': self.get_value()
  File "/config/custom_components/yandex_smart_home/prop.py", line 157, in get_value
    raise SmartHomeError(ERR_NOT_SUPPORTED_IN_CURRENT_MODE, "Invalid value")
custom_components.yandex_smart_home.error.SmartHomeError: Invalid value
2021-04-18 14:47:27 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 37, in listener
    await notifier.async_event_handler(event)
  File "/config/custom_components/yandex_smart_home/notifier.py", line 116, in async_event_handler
    if old_entity.query_serialize() != device: # есть изменения
  File "/config/custom_components/yandex_smart_home/helpers.py", line 221, in query_serialize
    properties.append(ppt.get_state())
  File "/config/custom_components/yandex_smart_home/prop.py", line 94, in get_state
    'value': self.get_value()
  File "/config/custom_components/yandex_smart_home/prop.py", line 190, in get_value
    raise SmartHomeError(ERR_NOT_SUPPORTED_IN_CURRENT_MODE, "Invalid value")
custom_components.yandex_smart_home.error.SmartHomeError: Invalid value
...
2021-04-18 14:47:28 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 37, in listener
    await notifier.async_event_handler(event)
  File "/config/custom_components/yandex_smart_home/notifier.py", line 115, in async_event_handler
    device = entity.query_serialize()
  File "/config/custom_components/yandex_smart_home/helpers.py", line 221, in query_serialize
    properties.append(ppt.get_state())
  File "/config/custom_components/yandex_smart_home/prop.py", line 94, in get_state
    'value': self.get_value()
  File "/config/custom_components/yandex_smart_home/prop.py", line 157, in get_value
    raise SmartHomeError(ERR_NOT_SUPPORTED_IN_CURRENT_MODE, "Invalid value")
custom_components.yandex_smart_home.error.SmartHomeError: Invalid value
2021-04-18 14:47:28 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 37, in listener
    await notifier.async_event_handler(event)
  File "/config/custom_components/yandex_smart_home/notifier.py", line 115, in async_event_handler
    device = entity.query_serialize()
  File "/config/custom_components/yandex_smart_home/helpers.py", line 221, in query_serialize
    properties.append(ppt.get_state())
  File "/config/custom_components/yandex_smart_home/prop.py", line 94, in get_state
    'value': self.get_value()
  File "/config/custom_components/yandex_smart_home/prop.py", line 190, in get_value
    raise SmartHomeError(ERR_NOT_SUPPORTED_IN_CURRENT_MODE, "Invalid value")
custom_components.yandex_smart_home.error.SmartHomeError: Invalid value
2021-04-18 14:47:28 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 37, in listener
    await notifier.async_event_handler(event)
  File "/config/custom_components/yandex_smart_home/notifier.py", line 116, in async_event_handler
    if old_entity.query_serialize() != device: # есть изменения
  File "/config/custom_components/yandex_smart_home/helpers.py", line 221, in query_serialize
    properties.append(ppt.get_state())
  File "/config/custom_components/yandex_smart_home/prop.py", line 94, in get_state
    'value': self.get_value()
  File "/config/custom_components/yandex_smart_home/prop.py", line 157, in get_value
    raise SmartHomeError(ERR_NOT_SUPPORTED_IN_CURRENT_MODE, "Invalid value")
custom_components.yandex_smart_home.error.SmartHomeError: Invalid value
2021-04-18 14:47:28 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 37, in listener
    await notifier.async_event_handler(event)
  File "/config/custom_components/yandex_smart_home/notifier.py", line 116, in async_event_handler
    if old_entity.query_serialize() != device: # есть изменения
  File "/config/custom_components/yandex_smart_home/helpers.py", line 221, in query_serialize
    properties.append(ppt.get_state())
  File "/config/custom_components/yandex_smart_home/prop.py", line 94, in get_state
    'value': self.get_value()
  File "/config/custom_components/yandex_smart_home/prop.py", line 190, in get_value
    raise SmartHomeError(ERR_NOT_SUPPORTED_IN_CURRENT_MODE, "Invalid value")
custom_components.yandex_smart_home.error.SmartHomeError: Invalid value
2021-04-18 14:47:28 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 37, in listener
    await notifier.async_event_handler(event)
  File "/config/custom_components/yandex_smart_home/notifier.py", line 115, in async_event_handler
    device = entity.query_serialize()
  File "/config/custom_components/yandex_smart_home/helpers.py", line 221, in query_serialize
    properties.append(ppt.get_state())
  File "/config/custom_components/yandex_smart_home/prop.py", line 94, in get_state
    'value': self.get_value()
  File "/config/custom_components/yandex_smart_home/prop.py", line 157, in get_value
    raise SmartHomeError(ERR_NOT_SUPPORTED_IN_CURRENT_MODE, "Invalid value")
custom_components.yandex_smart_home.error.SmartHomeError: Invalid value
2021-04-18 14:47:28 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 37, in listener
    await notifier.async_event_handler(event)
  File "/config/custom_components/yandex_smart_home/notifier.py", line 115, in async_event_handler
    device = entity.query_serialize()
  File "/config/custom_components/yandex_smart_home/helpers.py", line 221, in query_serialize
    properties.append(ppt.get_state())
  File "/config/custom_components/yandex_smart_home/prop.py", line 94, in get_state
    'value': self.get_value()
  File "/config/custom_components/yandex_smart_home/prop.py", line 190, in get_value
    raise SmartHomeError(ERR_NOT_SUPPORTED_IN_CURRENT_MODE, "Invalid value")
custom_components.yandex_smart_home.error.SmartHomeError: Invalid value
2021-04-18 14:47:28 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 37, in listener
    await notifier.async_event_handler(event)
  File "/config/custom_components/yandex_smart_home/notifier.py", line 116, in async_event_handler
    if old_entity.query_serialize() != device: # есть изменения
  File "/config/custom_components/yandex_smart_home/helpers.py", line 221, in query_serialize
    properties.append(ppt.get_state())
  File "/config/custom_components/yandex_smart_home/prop.py", line 94, in get_state
    'value': self.get_value()
  File "/config/custom_components/yandex_smart_home/prop.py", line 157, in get_value
    raise SmartHomeError(ERR_NOT_SUPPORTED_IN_CURRENT_MODE, "Invalid value")
custom_components.yandex_smart_home.error.SmartHomeError: Invalid value
2021-04-18 14:47:28 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 37, in listener
    await notifier.async_event_handler(event)
  File "/config/custom_components/yandex_smart_home/notifier.py", line 116, in async_event_handler
    if old_entity.query_serialize() != device: # есть изменения
  File "/config/custom_components/yandex_smart_home/helpers.py", line 221, in query_serialize
    properties.append(ppt.get_state())
  File "/config/custom_components/yandex_smart_home/prop.py", line 94, in get_state
    'value': self.get_value()
  File "/config/custom_components/yandex_smart_home/prop.py", line 190, in get_value
    raise SmartHomeError(ERR_NOT_SUPPORTED_IN_CURRENT_MODE, "Invalid value")
custom_components.yandex_smart_home.error.SmartHomeError: Invalid value
2021-04-18 14:47:29 INFO (MainThread) [custom_components.yandex_smart_home.notifier] Update climate.tuya_radiator_1_climate: off
2021-04-18 14:47:29 INFO (MainThread) [custom_components.yandex_smart_home.notifier] Update climate.tuya_radiator_1_climate: unknown
2021-04-18 14:47:29 INFO (MainThread) [custom_components.yandex_smart_home.notifier] Update climate.tuya_radiator_2_climate: off
2021-04-18 14:47:29 INFO (MainThread) [custom_components.yandex_smart_home.notifier] Update climate.tuya_radiator_3_climate: off
2021-04-18 14:47:29 INFO (MainThread) [custom_components.yandex_smart_home.notifier] Update climate.tuya_radiator_1_climate: unknown
2021-04-18 14:47:29 INFO (MainThread) [custom_components.yandex_smart_home.notifier] Update climate.tuya_radiator_3_climate: unknown
2021-04-18 14:47:29 INFO (MainThread) [custom_components.yandex_smart_home.notifier] Update climate.tuya_radiator_2_climate: unknown
2021-04-18 14:47:29 INFO (MainThread) [custom_components.yandex_smart_home.notifier] Update climate.tuya_radiator_2_climate: unknown
2021-04-18 14:47:29 INFO (MainThread) [custom_components.yandex_smart_home.notifier] Update climate.tuya_radiator_3_climate: unknown
...
```

**Comment by glebsterx** [comment]
Ну честно говоря не могу понять с ходу в чем проблема - ошибку дает запрос значения температуры и влажности в домене climate.. Раньше (или при отключенном нотификаторе) при попытке просмотра через УДЯ таких ошибок не было?

**Comment by PaulAnnekov** [comment]
> Раньше (или при отключенном нотификаторе) при попытке просмотра через УДЯ таких ошибок не было?

Нет.

> Все остальное же норм работает?

Да.

Я не разбирался в коде, но может быть такое, что просто при старте некоторые датчики в статусе unknown/unavailable и с новым изменением yandex_smart_home пытается прям на старте считать их статус и отправить в УДЯ?

**Comment by glebsterx** [comment]
> Я не разбирался в коде, но может быть такое, что просто при старте некоторые датчики в статусе unknown/unavailable и с новым изменением yandex_smart_home пытается прям на старте считать их статус и отправить в УДЯ?

Да, скорее всего так и есть - я сейчас сделал дополнительные условия как раз по этим состояниям. Щас протестирую и сделаю патч. Если вкратце в notifier.py 

строка 3 добавить `STATE_UNKNOWN`
в а функция async_event_handler теперь выглядит так:
```
    async def async_event_handler(self, event: Event):
        devices = []
        entity_id = event.data.get('entity_id')
        old_state = event.data.get('old_state')
        new_state = event.data.get('new_state')
        if not old_state or old_state.state in [STATE_UNAVAILABLE, STATE_UNKNOWN, None]:
            return
        if not new_state or new_state.state in [STATE_UNAVAILABLE, STATE_UNKNOWN, None]:
            return
        if entity_id in CLOUD_NEVER_EXPOSED_ENTITIES or not self.hass.data[DOMAIN][DATA_CONFIG].should_expose(entity_id):
            return
        old_entity = YandexEntity(self.hass, self.hass.data[DOMAIN][DATA_CONFIG], old_state)
        entity = YandexEntity(self.hass, self.hass.data[DOMAIN][DATA_CONFIG], new_state)
        device = entity.query_serialize()
        if old_entity.query_serialize() != device: # есть изменения
            if device['capabilities'] or device['properties']:
                devices.append(device)
                if devices:
                    await self.async_notify_skill(devices)
                    _LOGGER.info("Update "+entity_id+": "+new_state.state)
```
Если возможно - протестируйте плиз

**Comment by PaulAnnekov** [comment]
Протестировал, работает, спасибо.

**Comment by glebsterx** [comment]
Вам спасибо =)
Создал PR #179 с этими правками
