### ISSUE TITLE
После последней серии обновлений перестали переключаться режимы кондиционера

### ISSUE THREAD

**Issue by baskalex** [dmitry-k/yandex_smart_home#228]
Всем привет. После обновления от 20 июня на всех кондиционерах перестали переключаться режимы (холод, тепло, осушение и т.д.). При попытке изменения режима вылетает ошибка. При этом, включение/выключение, изменение температуры работают нормально. Полагаю, виноваты комнаты 63618f4 и 4b1bc25. Откатился на предыдущую версию, всё вернулось на круги своя.

**Comment by dmitry-k** [comment]
Приложите пожалуйста логи ошибок. Я конечно могу ревертнуть эти коммиты, но лучше исправить. А без логов непонятно что конкретно у вас происходит.

**Comment by AntoxaSa** [comment]
Дмитрий откуда лог взять? Когда я захожу в яндексе обновить список просто нет термостатов.(Climate)

**Comment by dmitry-k** [comment]
В логе HA никаких ошибок при этом не появляется?

**Comment by AntoxaSa** [comment]
> В логе HA никаких ошибок при этом не появляется?

2021-06-23 21:35:05 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration yandex_smart_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
Больше ничего в логе не вижу связанного с yandex_smart_home

**Comment by dmitry-k** [comment]
Ревертнул 4b1bc25, скорее всего в нём был дело

**Comment by AntoxaSa** [comment]
Вообщем термостат термоголовку появился в списке а кондиционер так и не появляется(

**Comment by AntoxaSa** [comment]
Logger: homeassistant.components.mqtt.climate
Source: components/mqtt/climate.py:453
Integration: MQTT (documentation, issues)
First occurred: 21:44:23 (4 occurrences)
Last logged: 21:44:26

Invalid fan_modes mode:
Invalid swing_modes mode:

**Comment by AntoxaSa** [comment]
Logger: homeassistant.components.mqtt.climate
Source: components/mqtt/climate.py:399
Integration: MQTT (documentation, issues)
First occurred: 21:44:23 (4 occurrences)
Last logged: 21:44:26

Could not parse temperature from

**Comment by dmitry-k** [comment]
Попробуйте включить дебаг лог в configuration.yaml

```
logger:
  default: critical
  logs:
    custom_components.yandex_smart_home: debug
```

или что посмотрите консоль в яндексе.

Интересно, что компонент выдаёт при обновлении устройств. Есть там кондиционер и какие данные для него передаются?

**Comment by AntoxaSa** [comment]
Logger: aiohttp.server
Source: custom_components/yandex_smart_home/http.py:58
Integration: Yandex Smart Home (documentation)
First occurred: 21:45:23 (1 occurrences)
Last logged: 21:45:23

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/config/custom_components/yandex_smart_home/http.py", line 58, in post
    message = await request.json()  # type: dict
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_request.py", line 614, in json
    return loads(body)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by AntoxaSa** [comment]
2021-06-23 21:56:47 DEBUG (MainThread) [custom_components.yandex_smart_home.notifier] Notifier disabled: no config
2021-06-23 21:57:23 DEBUG (MainThread) [custom_components.yandex_smart_home.http] Request: http://smarthome96.duckdns.org/api/yandex_smart_home/v1.0/user/devices/action (POST data: {'payload': {'devices': [{'id': 'light.nastolnaia_lampa', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}]}]}})
2021-06-23 21:57:23 DEBUG (MainThread) [custom_components.yandex_smart_home.http] Response: {'request_id': 'a61a56ec-e0f2-4f88-a11f-044528bf7fc5', 'payload': {'devices': [{'id': 'light.nastolnaia_lampa', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'action_result': {'status': 'DONE'}}}]}]}}
2021-06-23 21:57:27 DEBUG (MainThread) [custom_components.yandex_smart_home.http] Request: http://smarthome96.duckdns.org/api/yandex_smart_home/v1.0/user/devices/query (POST data: {'devices': [{'id': 'media_player.yandex_intents'}, {'id': 'light.nastolnaia_lampa'}, {'id': 'switch.komnata_liustra_right'}, {'id': 'switch.termogolovka_komnata_auto_lock'}, {'id': 'switch.prikhozhaia_svet'}, {'id': 'switch.komnata_liustra_left'}, {'id': 'switch.vytiazhka_na_kukhne'}, {'id': 'switch.tualet_svet_right'}, {'id': 'switch.xiaomi_airpurifier_led'}, {'id': 'switch.xiaomi_airpurifier_child_lock'}, {'id': 'switch.svet_i_vytiazhka_koridor_left'}, {'id': 'switch.tualet_svet_left'}, {'id': 'switch.kukhnia_svet'}, {'id': 'switch.0x588e81fffe4b882e_firmware_lock'}, {'id': 'switch.termogolovka_komnata_valve_detection'}, {'id': 'switch.xiaomi_airpurifier_ptc'}, {'id': 'switch.pc'}, {'id': 'fan.xiaomi_air_humidifier'}, {'id': 'switch.termogolovka_komnata_away_mode'}, {'id': 'switch.termogolovka_komnata_window_detection'}, {'id': 'fan.xiaomi_air_fresh'}, {'id': 'switch.svet_i_vytiazhka_koridor_right'}, {'id': 'switch.kn_radiator'}, {'id': 'media_player.yandex_station_ff98f029b3bab4f30a965b06'}, {'id': 'climate.termogolovka_komnata'}]})
2021-06-23 21:57:27 DEBUG (MainThread) [custom_components.yandex_smart_home.http] Response: {'request_id': '5d3f346d-2cff-4856-a6c3-32089ef636ed', 'payload': {'devices': [{'id': 'media_player.yandex_intents', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}, {'type': 'devices.capabilities.range', 'state': {'instance': 'volume', 'value': 0}}], 'properties': []}, {'id': 'light.nastolnaia_lampa', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}, {'type': 'devices.capabilities.range', 'state': {'instance': 'brightness', 'value': 79}}, {'type': 'devices.capabilities.color_setting', 'state': {'instance': 'temperature_k', 'value': 6535}}], 'properties': []}, {'id': 'switch.komnata_liustra_right', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': False}}], 'properties': []}, {'id': 'switch.termogolovka_komnata_auto_lock', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': False}}], 'properties': []}, {'id': 'switch.prikhozhaia_svet', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': False}}], 'properties': []}, {'id': 'switch.komnata_liustra_left', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': False}}], 'properties': []}, {'id': 'switch.vytiazhka_na_kukhne', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': False}}], 'properties': []}, {'id': 'switch.tualet_svet_right', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': False}}], 'properties': []}, {'id': 'switch.xiaomi_airpurifier_led', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}], 'properties': []}, {'id': 'switch.xiaomi_airpurifier_child_lock', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': False}}], 'properties': []}, {'id': 'switch.svet_i_vytiazhka_koridor_left', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': False}}], 'properties': []}, {'id': 'switch.tualet_svet_left', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': False}}], 'properties': []}, {'id': 'switch.kukhnia_svet', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': False}}], 'properties': []}, {'error_code': 'DEVICE_UNREACHABLE'}, {'id': 'switch.termogolovka_komnata_valve_detection', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': False}}], 'properties': []}, {'id': 'switch.xiaomi_airpurifier_ptc', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': False}}], 'properties': []}, {'id': 'switch.pc', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}], 'properties': []}, {'id': 'fan.xiaomi_air_humidifier', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}], 'properties': [{'type': 'devices.properties.float', 'state': {'instance': 'water_level', 'value': 23.0}}]}, {'id': 'switch.termogolovka_komnata_away_mode', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': False}}], 'properties': []}, {'id': 'switch.termogolovka_komnata_window_detection', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': False}}], 'properties': []}, {'id': 'fan.xiaomi_air_fresh', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': False}}], 'properties': []}, {'id': 'switch.svet_i_vytiazhka_koridor_right', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': False}}], 'properties': []}, {'id': 'switch.kn_radiator', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': False}}], 'properties': []}, {'id': 'media_player.yandex_station_ff98f029b3bab4f30a965b06', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}, {'type': 'devices.capabilities.toggle', 'state': {'instance': 'mute', 'value': False}}, {'type': 'devices.capabilities.toggle', 'state': {'instance': 'pause', 'value': True}}, {'type': 'devices.capabilities.range', 'state': {'instance': 'volume', 'value': 100}}], 'properties': []}, {'id': 'climate.termogolovka_komnata', 'capabilities': [{'type': 'devices.capabilities.on_off', 'state': {'instance': 'on', 'value': True}}, {'type': 'devices.capabilities.mode', 'state': {'instance': 'thermostat', 'value': 'heat'}}, {'type': 'devices.capabilities.range', 'state': {'instance': 'temperature', 'value': 0}}], 'properties': []}]}}
2021-06-23 21:57:34 DEBUG (MainThread) [custom_components.yandex_smart_home.http] Request: http://smarthome96.duckdns.org/api/yandex_smart_home/v1.0/user/devices
2021-06-23 21:57:34 DEBUG (MainThread) [custom_components.yandex_smart_home.capability] CONF_RELATIVE_VOLUME_ONLY: None
2021-06-23 21:57:34 DEBUG (MainThread) [custom_components.yandex_smart_home.capability] CONF_RELATIVE_VOLUME_ONLY: None
2021-06-23 21:57:34 DEBUG (MainThread) [custom_components.yandex_smart_home.smart_home] No mapping for <state switch.0x588e81fffe4b882e_firmware_lock=unavailable; restored=True, supported_features=0, friendly_name=Шлюз Firmware Lock, icon=mdi:cloud-lock @ 2021-06-23T21:57:03.955877+05:00> domain
2021-06-23 21:57:34 DEBUG (MainThread) [custom_components.yandex_smart_home.smart_home] No mapping for <state switch.0x158d0003ccf6f4_switch=unavailable; restored=True, supported_features=0, friendly_name=Кухня Switch @ 2021-06-23T21:57:03.956036+05:00> domain
2021-06-23 21:57:34 DEBUG (MainThread) [custom_components.yandex_smart_home.smart_home] No mapping for <state switch.0x158d0003cd0c11_switch=unavailable; restored=True, supported_features=0, friendly_name=Вытяжка Switch @ 2021-06-23T21:57:03.956344+05:00> domain
2021-06-23 21:57:34 DEBUG (MainThread) [custom_components.yandex_smart_home.smart_home] No mapping for <state switch.0x158d0003cd139b_switch=unavailable; restored=True, supported_features=0, friendly_name=Прихожая Switch @ 2021-06-23T21:57:03.956652+05:00> domain
2021-06-23 21:57:34 DEBUG (MainThread) [custom_components.yandex_smart_home.smart_home] No mapping for <state switch.0x158d000405604b_channel_1=unavailable; restored=True, supported_features=0, friendly_name=Комната Channel 1 @ 2021-06-23T21:57:03.957479+05:00> domain
2021-06-23 21:57:34 DEBUG (MainThread) [custom_components.yandex_smart_home.smart_home] No mapping for <state switch.0x158d000405604b_channel_2=unavailable; restored=True, supported_features=0, friendly_name=Комната Channel 2 @ 2021-06-23T21:57:03.957646+05:00> domain
2021-06-23 21:57:34 DEBUG (MainThread) [custom_components.yandex_smart_home.smart_home] No mapping for <state switch.0x158d000450b3b6_channel_1=unavailable; restored=True, supported_features=0, friendly_name=Aqara Wall Switch (No Neutral, Double Rocker)2 Channel 1 @ 2021-06-23T21:57:03.957962+05:00> domain
2021-06-23 21:57:34 DEBUG (MainThread) [custom_components.yandex_smart_home.smart_home] No mapping for <state switch.0x158d000450b3b6_channel_2=unavailable; restored=True, supported_features=0, friendly_name=Aqara Wall Switch (No Neutral, Double Rocker)2 Channel 2 @ 2021-06-23T21:57:03.958116+05:00> domain
2021-06-23 21:57:34 DEBUG (MainThread) [custom_components.yandex_smart_home.http] Response: {'request_id': '79a50329-d502-4507-bc0f-d991ff843e0e', 'payload': {'user_id': 'ecf70f2ac45a488782558bb3a7b75ce3', 'devices': [{'id': 'switch.pc', 'name': 'PC', 'type': 'devices.types.switch', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}], 'properties': [], 'device_info': {'manufacturer': 'switch.pc', 'model': ''}}, {'id': 'fan.xiaomi_air_fresh', 'name': 'Xiaomi Air Fresh', 'type': 'devices.types.humidifier', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}], 'properties': [], 'device_info': {'manufacturer': 'fan.xiaomi_air_fresh', 'model': ''}}, {'id': 'fan.xiaomi_air_humidifier', 'name': 'Xiaomi Air Humidifier', 'type': 'devices.types.humidifier', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}], 'properties': [{'type': 'devices.properties.float', 'retrievable': True, 'reportable': False, 'parameters': {'instance': 'water_level', 'unit': 'unit.percent'}}], 'device_info': {'manufacturer': 'fan.xiaomi_air_humidifier', 'model': ''}}, {'id': 'switch.xiaomi_airpurifier_child_lock', 'name': 'Child lock', 'type': 'devices.types.switch', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}], 'properties': [], 'device_info': {'manufacturer': 'switch.xiaomi_airpurifier_child_lock', 'model': ''}}, {'id': 'switch.xiaomi_airpurifier_ptc', 'name': 'PTC', 'type': 'devices.types.switch', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}], 'properties': [], 'device_info': {'manufacturer': 'switch.xiaomi_airpurifier_ptc', 'model': ''}}, {'id': 'switch.xiaomi_airpurifier_led', 'name': 'led_brightness', 'type': 'devices.types.switch', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}], 'properties': [], 'device_info': {'manufacturer': 'switch.xiaomi_airpurifier_led', 'model': ''}}, {'id': 'switch.kn_radiator', 'name': 'Кухня головка радиатора', 'type': 'devices.types.switch', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}], 'properties': [], 'device_info': {'manufacturer': 'switch.kn_radiator', 'model': ''}}, {'id': 'climate.hvac_lr', 'name': 'hvac_lr', 'type': 'devices.types.thermostat', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}, {'type': 'devices.capabilities.mode', 'retrievable': True, 'reportable': False, 'parameters': {'instance': 'thermostat', 'modes': [{'value': 'auto'}, {'value': 'cool'}, {'value': 'heat'}, {'value': 'dry'}], 'ordered': False}}, {'type': 'devices.capabilities.mode', 'retrievable': True, 'reportable': False, 'parameters': {'instance': 'swing', 'modes': [{'value': 'both'}], 'ordered': False}}, {'type': 'devices.capabilities.mode', 'retrievable': True, 'reportable': False, 'parameters': {'instance': 'fan_speed', 'modes': [{'value': 'auto'}], 'ordered': True}}, {'type': 'devices.capabilities.range', 'retrievable': True, 'reportable': False, 'parameters': {'instance': 'temperature', 'unit': 'unit.temperature.celsius', 'range': {'min': 16.0, 'max': 31.0, 'precision': 1.0}}}], 'properties': [{'type': 'devices.properties.float', 'retrievable': True, 'reportable': False, 'parameters': {'instance': 'temperature', 'unit': 'unit.temperature.celsius'}}], 'device_info': {'manufacturer': 'climate.hvac_lr', 'model': ''}}, {'id': 'climate.termogolovka_komnata', 'name': 'Termogolovka_komnata', 'type': 'devices.types.thermostat', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}, {'type': 'devices.capabilities.mode', 'retrievable': True, 'reportable': False, 'parameters': {'instance': 'thermostat', 'modes': [{'value': 'heat'}, {'value': 'auto'}], 'ordered': False}}, {'type': 'devices.capabilities.range', 'retrievable': True, 'reportable': False, 'parameters': {'instance': 'temperature', 'unit': 'unit.temperature.celsius', 'range': {'min': 5.0, 'max': 35.0, 'precision': 0.5}}}], 'properties': [], 'device_info': {'manufacturer': 'climate.termogolovka_komnata', 'model': ''}}, {'id': 'light.nastolnaia_lampa', 'name': 'настольная_лампа', 'type': 'devices.types.light', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}, {'type': 'devices.capabilities.range', 'retrievable': True, 'reportable': False, 'parameters': {'instance': 'brightness', 'unit': 'unit.percent', 'range': {'min': 0, 'max': 100, 'precision': 1}}}, {'type': 'devices.capabilities.color_setting', 'retrievable': True, 'reportable': False, 'parameters': {'temperature_k': {'min': 2000, 'max': 6666}}}], 'properties': [], 'device_info': {'manufacturer': 'light.nastolnaia_lampa', 'model': ''}}, {'id': 'switch.termogolovka_komnata_window_detection', 'name': 'Termogolovka_komnata_window_detection', 'type': 'devices.types.switch', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}], 'properties': [], 'device_info': {'manufacturer': 'switch.termogolovka_komnata_window_detection', 'model': ''}}, {'id': 'switch.termogolovka_komnata_valve_detection', 'name': 'Termogolovka_komnata_valve_detection', 'type': 'devices.types.switch', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}], 'properties': [], 'device_info': {'manufacturer': 'switch.termogolovka_komnata_valve_detection', 'model': ''}}, {'id': 'switch.termogolovka_komnata_auto_lock', 'name': 'Termogolovka_komnata_auto_lock', 'type': 'devices.types.switch', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}], 'properties': [], 'device_info': {'manufacturer': 'switch.termogolovka_komnata_auto_lock', 'model': ''}}, {'id': 'switch.termogolovka_komnata_away_mode', 'name': 'Termogolovka_komnata_away_mode', 'type': 'devices.types.switch', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}], 'properties': [], 'device_info': {'manufacturer': 'switch.termogolovka_komnata_away_mode', 'model': ''}}, {'id': 'switch.tualet_svet_left', 'name': 'Туалет_свет_left', 'type': 'devices.types.switch', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}], 'properties': [], 'device_info': {'manufacturer': 'switch.tualet_svet_left', 'model': ''}}, {'id': 'switch.tualet_svet_right', 'name': 'Туалет_свет_right', 'type': 'devices.types.switch', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}], 'properties': [], 'device_info': {'manufacturer': 'switch.tualet_svet_right', 'model': ''}}, {'id': 'switch.komnata_liustra_left', 'name': 'комната_люстра_left', 'type': 'devices.types.switch', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}], 'properties': [], 'device_info': {'manufacturer': 'switch.komnata_liustra_left', 'model': ''}}, {'id': 'switch.komnata_liustra_right', 'name': 'комната_люстра_right', 'type': 'devices.types.switch', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}], 'properties': [], 'device_info': {'manufacturer': 'switch.komnata_liustra_right', 'model': ''}}, {'id': 'switch.kukhnia_svet', 'name': 'Кухня_свет', 'type': 'devices.types.switch', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}], 'properties': [], 'device_info': {'manufacturer': 'switch.kukhnia_svet', 'model': ''}}, {'id': 'switch.prikhozhaia_svet', 'name': 'прихожая_свет', 'type': 'devices.types.switch', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}], 'properties': [], 'device_info': {'manufacturer': 'switch.prikhozhaia_svet', 'model': ''}}, {'id': 'switch.vytiazhka_na_kukhne', 'name': 'вытяжка_на_кухне', 'type': 'devices.types.switch', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}], 'properties': [], 'device_info': {'manufacturer': 'switch.vytiazhka_na_kukhne', 'model': ''}}, {'id': 'switch.svet_i_vytiazhka_koridor_left', 'name': 'свет_и_вытяжка_коридор_left', 'type': 'devices.types.switch', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}], 'properties': [], 'device_info': {'manufacturer': 'switch.svet_i_vytiazhka_koridor_left', 'model': ''}}, {'id': 'switch.svet_i_vytiazhka_koridor_right', 'name': 'свет_и_вытяжка_коридор_right', 'type': 'devices.types.switch', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}], 'properties': [], 'device_info': {'manufacturer': 'switch.svet_i_vytiazhka_koridor_right', 'model': ''}}, {'id': 'media_player.yandex_intents', 'name': 'Yandex Intents', 'type': 'devices.types.media_device', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}, {'type': 'devices.capabilities.range', 'retrievable': True, 'reportable': False, 'parameters': {'instance': 'volume', 'random_access': True, 'range': {'max': 100, 'min': 0, 'precision': 1}}}], 'properties': [], 'device_info': {'manufacturer': 'media_player.yandex_intents', 'model': ''}}, {'id': 'media_player.yandex_station_ff98f029b3bab4f30a965b06', 'name': 'Яндекс Мини', 'type': 'devices.types.media_device', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True, 'reportable': False}, {'type': 'devices.capabilities.toggle', 'retrievable': True, 'reportable': False, 'parameters': {'instance': 'mute'}}, {'type': 'devices.capabilities.toggle', 'retrievable': True, 'reportable': False, 'parameters': {'instance': 'pause'}}, {'type': 'devices.capabilities.range', 'retrievable': True, 'reportable': False, 'parameters': {'instance': 'volume', 'random_access': True, 'range': {'max': 100, 'min': 0, 'precision': 1}}}, {'type': 'devices.capabilities.range', 'retrievable': None, 'reportable': False, 'parameters': {'instance': 'channel', 'random_access': False}}], 'properties': [], 'device_info': {'manufacturer': 'media_player.yandex_station_ff98f029b3bab4f30a965b06', 'model': ''}}]}}

**Comment by dmitry-k** [comment]
Спасибо, ревертнул и 63618f4.
Похоже он возвращал неподдерживаемое яндексом значение для swing.

**Comment by AntoxaSa** [comment]
Теперь работает, как и раньше все ок

**Comment by igoralexeev** [comment]
Подтверждаю
а последняя версия вообще все поломала

**Comment by igoralexeev** [comment]
у меня странный глюк который скорее всего имеет отношение больше к Яндексу
итак  команда "какой статус кондиционера"  - работает
комнадна "включи кондиционер" - не справилась
помогает переименование в "кондей" но жена филолог и лютует от этого слова

**Comment by dext0r** [comment]
Ещё актуально?

**Comment by baskalex** [comment]
Нет, уже всё ок, можно закрывать.
________________________________
