### ISSUE TITLE
Не обновляется список устройств при наличии объекта air_quality

### ISSUE THREAD

**Issue by zloalder** [dmitry-k/yandex_smart_home#231]
Если в HA есть объект в домене air_quality, то при попытке обновить список устройств возникает ошибка:
"Не получилось обновить список устройств. Подождите немного и попробуйте ещё раз."

В логе ошибка:
ERROR (MainThread) [custom_components.yandex_smart_home.smart_home] Handler process unexpected error
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/smart_home.py", line 49, in _process
    result = await handler(hass, data, message)
  File "/config/custom_components/yandex_smart_home/smart_home.py", line 89, in async_devices_sync
    serialized = await entity.devices_serialize(entity_reg, dev_reg)
  File "/config/custom_components/yandex_smart_home/helpers.py", line 138, in devices_serialize
    device_type = get_yandex_type(domain, device_class)
  File "/config/custom_components/yandex_smart_home/helpers.py", line 48, in get_yandex_type
    DOMAIN_TO_YANDEX_TYPES[domain]
KeyError: 'air_quality'

Workaround: отключить домен air_quality в настройках

**Comment by glebsterx** [comment]
@zloalder у меня нет таких устройств, писал по документации, поэтому проверить полностью не было возможности, а все, кто тестировал - подключали через домен `sensor`. А что у Вас за устройство?
Короче мой косяк - забыл добавить маппинг. Исправил в #232

**Comment by zloalder** [comment]
@glebsterx это Xiaomi ClearGrass Air Detector. Раньше он был как sensor, а теперь как air_quality.

Теперь такая ошибка:
ERROR (MainThread) [homeassistant.setup] Setup failed for yandex_smart_home: unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 200, in _async_setup_component
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/yandex_smart_home/__init__.py", line 12, in <module>
    from .const import (
  File "/config/custom_components/yandex_smart_home/const.py", line 146, in <module>
    air_quality.DOMAIN: TYPE_SENSOR,
NameError: name 'air_quality' is not defined

**Comment by zloalder** [comment]
Поосле добавления 'air_quality' в import (const.py:20) все заработало. Теперь в яндексе все красиво:
![image](https://user-images.githubusercontent.com/56175992/123223842-e92d8b80-d4d9-11eb-9a2d-a78892fe7777.png)
