### ISSUE TITLE
b63dab3 - шеф! все пропало!

### ISSUE THREAD

**Issue by igoralexeev** [dmitry-k/yandex_smart_home#233]
последняя версия b63dab3  вообще ничего не видно в консоли яндекса

**Comment by megachammer** [comment]
Подтверждаю, все пропало. Алиса совершенно ничего больше не может в HomeAssistant

**Comment by dmitry-k** [comment]
Было поломано в #231

**Comment by akarpych** [comment]
Эта ошибка возникла в кастомной интеграции.

Logger: homeassistant
Source: custom_components/yandex_smart_home/capability.py:1343
Integration: Yandex Smart Home (documentation)
First occurred: 13:48:45 (2 occurrences)
Last logged: 13:48:45

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 40, in state_change_listener
    await notifier.async_event_handler(event)
  File "/config/custom_components/yandex_smart_home/notifier.py", line 139, in async_event_handler
    device = yandex_entity.notification_serialize(event_entity_id)
  File "/config/custom_components/yandex_smart_home/helpers.py", line 242, in notification_serialize
    cpb_state = cpb.get_state()
  File "/config/custom_components/yandex_smart_home/capability.py", line 98, in get_state
    value = self.get_value()
  File "/config/custom_components/yandex_smart_home/capability.py", line 1343, in get_value
    kelvin = self.state.attributes[light.ATTR_MAX_MIREDS]
KeyError: 'max_mireds'
  
У меня вот такое получается

**Comment by igoralexeev** [comment]
переустановил компонент - заработало вроде бы
