### ISSUE TITLE
Неправильно парсится файл automations.yaml

### ISSUE THREAD

**Issue by byaaka** [dmitry-k/yandex_smart_home#296]
Постоянно шлёт ошибку. Как я понимаю как-то неправильно парсит файл automations.yaml
Home Assistant установлен на компе под OpenSuSE 15.2 с питоном 3.9.6
Сперва лог:
2021-08-20T20:34:40.949174+07:00 MediaServer hass[5377]: 2021-08-20 20:34:40 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
2021-08-20T20:34:40.949430+07:00 MediaServer hass[5377]: Traceback (most recent call last):
2021-08-20T20:34:40.949538+07:00 MediaServer hass[5377]:   File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/capability.py", line 876, in float_value
2021-08-20T20:34:40.949631+07:00 MediaServer hass[5377]:     return float(value)
2021-08-20T20:34:40.949740+07:00 MediaServer hass[5377]: ValueError: could not convert string to float: 'https://streamer01.1028.fm:8443/arstream'
2021-08-20T20:34:40.949834+07:00 MediaServer hass[5377]: During handling of the above exception, another exception occurred:
2021-08-20T20:34:40.949921+07:00 MediaServer hass[5377]: Traceback (most recent call last):
2021-08-20T20:34:40.950011+07:00 MediaServer hass[5377]:   File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/notifier.py", line 168, in state_change_listener
2021-08-20T20:34:40.950103+07:00 MediaServer hass[5377]:     await asyncio.gather(*[n.async_event_handler(event) for n in hass.data[DOMAIN][NOTIFIERS]])
2021-08-20T20:34:40.950191+07:00 MediaServer hass[5377]:   File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/notifier.py", line 130, in async_event_handler
2021-08-20T20:34:40.950282+07:00 MediaServer hass[5377]:     device = yandex_entity.notification_serialize(event_entity_id)
2021-08-20T20:34:40.950372+07:00 MediaServer hass[5377]:   File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/helpers.py", line 275, in notification_serialize
2021-08-20T20:34:40.950462+07:00 MediaServer hass[5377]:     cpb_state = cpb.get_state()
2021-08-20T20:34:40.950552+07:00 MediaServer hass[5377]:   File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/capability.py", line 115, in get_state
2021-08-20T20:34:40.950637+07:00 MediaServer hass[5377]:     value = self.get_value()
2021-08-20T20:34:40.950727+07:00 MediaServer hass[5377]:   File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/capability.py", line 1183, in get_value
2021-08-20T20:34:40.950817+07:00 MediaServer hass[5377]:     return self.float_value(self.state.attributes.get(media_player.ATTR_MEDIA_CONTENT_ID))
2021-08-20T20:34:40.950917+07:00 MediaServer hass[5377]:   File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/capability.py", line 878, in float_value
2021-08-20T20:34:40.951004+07:00 MediaServer hass[5377]:     raise SmartHomeError(
2021-08-20T20:34:40.951094+07:00 MediaServer hass[5377]: custom_components.yandex_smart_home.error.SmartHomeError: Unsupported value 'https://streamer01.1028.fm:8443/arstream' for instance channel of media_player.mpd

Фрагмент файла автоматизации:
- id: '1629036215733'
  alias: Включи радио
  description: включение радио по кнопке
  trigger:
  - platform: device
    domain: mqtt
    device_id: 7a9270c05ab27efc90e0741603af7a2e
    type: button_short_press
    subtype: Button
    discovery_id: lumi_button action_1
    id: радиовключено
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: lumi/audio/play/set
      payload: '{"url": "https://streamer01.1028.fm:8443/arstream", "volume": 50}'
  mode: restart

Т.е. автоматизация должна запустить на шлюзе по нажатию кнопки радио (работает).
Шлюз перепрошитый на OpenWRT из набора сенсоров Xiaomi.
На нем MQTT агент https://github.com/Beetle-II/lumi (пример радио из readme)

**Comment by dext0r** [comment]
Компонент обновлён до 0.1.3?

**Comment by dext0r** [comment]
Покажите список атрибутов для `media_player.mpd` из Панели разработчика

**Comment by byaaka** [comment]
friendly_name: MPD 
supported_features: 325567
