### ISSUE TITLE
Ошибка при перезапуске сервера после обновления версия до 0.1.4

### ISSUE THREAD

**Issue by byaaka** [dmitry-k/yandex_smart_home#299]
Сегодня увидел обновление до версии 0.1.4 и обновился. По логу появились ошибки при запуске HA.
К сожалению из лога не понятно что не нравиться. Если что-то нужно ещё - добавлю.

Системный лог:
2021-08-24T11:03:43.242431+07:00 MediaServer hass[5377]: 2021-08-24 11:03:43 ERROR (MainThread) [custom_components.yandex_smart_home.smart_home] Handler process unexpected error
2021-08-24T11:03:43.242604+07:00 MediaServer hass[5377]: Traceback (most recent call last):
2021-08-24T11:03:43.242705+07:00 MediaServer hass[5377]:   File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/smart_home.py", line 45, in _process
2021-08-24T11:03:43.242775+07:00 MediaServer hass[5377]:     result = await handler(hass, data, message)
2021-08-24T11:03:43.242843+07:00 MediaServer hass[5377]:   File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/smart_home.py", line 85, in async_devices_sync
2021-08-24T11:03:43.242905+07:00 MediaServer hass[5377]:     serialized = await entity.devices_serialize(entity_reg, dev_reg)
2021-08-24T11:03:43.242966+07:00 MediaServer hass[5377]:   File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/helpers.py", line 193, in devices_serialize
2021-08-24T11:03:43.243026+07:00 MediaServer hass[5377]:     description = cpb.description()
2021-08-24T11:03:43.243085+07:00 MediaServer hass[5377]:   File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/capability.py", line 107, in description
2021-08-24T11:03:43.243146+07:00 MediaServer hass[5377]:     parameters = self.parameters()
2021-08-24T11:03:43.243230+07:00 MediaServer hass[5377]:   File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/capability.py", line 1265, in parameters
2021-08-24T11:03:43.243309+07:00 MediaServer hass[5377]:     max_temp = self.state.attributes[light.ATTR_MIN_MIREDS]
2021-08-24T11:03:43.243370+07:00 MediaServer hass[5377]: KeyError: 'min_mireds'
2021-08-24T11:03:43.243459+07:00 MediaServer hass[5377]: 2021-08-24 11:03:43 ERROR (MainThread) [custom_components.yandex_smart_home.smart_home] Error handling message {}: {'error_code': 'INTERNAL_ERROR'}

Ошибка из HA:

Logger: custom_components.yandex_smart_home.smart_home
Source: custom_components/yandex_smart_home/capability.py:1265
Integration: Yandex Smart Home (documentation, issues)
First occurred: 11:03:43 (1 occurrences)
Last logged: 11:03:43
Handler process unexpected error

Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/smart_home.py", line 45, in _process
    result = await handler(hass, data, message)
  File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/smart_home.py", line 85, in async_devices_sync
    serialized = await entity.devices_serialize(entity_reg, dev_reg)
  File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/helpers.py", line 193, in devices_serialize
    description = cpb.description()
  File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/capability.py", line 107, in description
    parameters = self.parameters()
  File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/capability.py", line 1265, in parameters
    max_temp = self.state.attributes[light.ATTR_MIN_MIREDS]
KeyError: 'min_mireds'

**Comment by byaaka** [comment]
В дополнении Home Assistant 2021.8.8

**Comment by dext0r** [comment]
Странно, но код, вызывающий ошибку, не менялся в 0.1.4. Попробуйте поставить из мастера, ошибка должна уйти.

**Comment by dext0r** [comment]
Поправлено в v0.1.5
