### ISSUE TITLE
hass 0.100.0b

### ISSUE THREAD

**Issue by Elesarf** [dmitry-k/yandex_smart_home#33]
Попытка подключить компонент терпит фиаско со следующей ошибкой:
```
2019-10-08 21:42:37 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for yandex_smart_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-10-08 21:42:37 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 40, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 231, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 128, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/core.py", line 29, in post
    errors = await async_check_ha_config_file(request.app["hass"])
  File "/usr/src/homeassistant/homeassistant/config.py", line 818, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 113, in async_check_ha_config_file
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 223, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/yandex_smart_home/__init__.py", line 16, in <module>
    from .http import async_register_http
  File "/config/custom_components/yandex_smart_home/http.py", line 14, in <module>
    from .smart_home import async_handle_message
  File "/config/custom_components/yandex_smart_home/smart_home.py", line 13, in <module>
    from .helpers import RequestData, YandexEntity
  File "/config/custom_components/yandex_smart_home/helpers.py", line 11, in <module>
    from . import capability
ValueError: source code string cannot contain null bytes
```

**Comment by dmitry-k** [comment]
Возможно файлы компонента повреждены. Попробуйте поставить его заново.

**Comment by Elesarf** [comment]
Действительно, заново склонировал и заработало. Видимо при обновлении что то поломал.
