### ISSUE TITLE
Failed to connect to Yandex Smart Home cloud

### ISSUE THREAD

**Issue by slavak78** [dmitry-k/yandex_smart_home#342]
Вот такая ошибка периодически возникает. Возникает конечно не только на этом компоненте, но может Вы все-таки сможете помочь? Home Assistant Core

Logger: custom_components.yandex_smart_home.cloud
Source: custom_components/yandex_smart_home/cloud.py:80
Integration: Yandex Smart Home (documentation, issues)
First occurred: 6 декабря 2021 г., 22:27:09 (14 occurrences)
Last logged: 09:07:21

Failed to connect to Yandex Smart Home cloud
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/yandex_smart_home/cloud.py", line 80, in connect
    self._ws = await self._session.ws_connect(self._url, heartbeat=45, headers={
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/client.py", line 754, in _ws_connect
    resp = await self.request(
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host yaha-cloud.ru:443 ssl:default [Temporary failure in name resolution]

**Comment by dext0r** [comment]
Скорее всего используемые вами DNS серверы иногда не отвечают. Поэтому вы и получаете такую ошибку. Эта проблема не в компоненте, поэтому ишью закрываю. 

Тематические чаты по HA, в которых могут помочь:
* https://t.me/SprutAI_HomeAssistant
* https://t.me/homassistant
