### ISSUE TITLE
Внезапно сломалась интеграция

### ISSUE THREAD

**Issue by alting** [dmitry-k/yandex_smart_home#354]
## System Health

version | core-2021.12.8
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
user | homeassistant
virtualenv | true
python_version | 3.9.7
os_name | Linux
os_version | 5.10.0-1049-oem
arch | x86_64
timezone | Europe/Moscow

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 3667
Installed Version | 1.19.1
Stage | running
Available Repositories | 1008
Downloaded Repositories | 78

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 41
views | 46
mode | storage

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.5.0
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 53

</details>

2022-01-09 11:58:35 ERROR (MainThread) [homeassistant.config] Unknown error calling yandex_smart_home CONFIG_SCHEMA
Traceback (most recent call last):
  File "/srv/homeassistant-3.9.7/lib/python3.9/site-packages/homeassistant/config.py", line 842, in async_process_component_config
    return component.CONFIG_SCHEMA(config)  # type: ignore
  File "/srv/homeassistant-3.9.7/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/srv/homeassistant-3.9.7/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/srv/homeassistant-3.9.7/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 386, in validate_mapping
    cval = cvalue(key_path, value)
  File "/srv/homeassistant-3.9.7/lib/python3.9/site-packages/voluptuous/validators.py", line 215, in _run
    return self._exec(self._compiled, value, path)
  File "/srv/homeassistant-3.9.7/lib/python3.9/site-packages/voluptuous/validators.py", line 339, in _exec
    v = func(path, v)
  File "/srv/homeassistant-3.9.7/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/srv/homeassistant-3.9.7/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/srv/homeassistant-3.9.7/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/srv/homeassistant-3.9.7/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 386, in validate_mapping
    cval = cvalue(key_path, value)
  File "/srv/homeassistant-3.9.7/lib/python3.9/site-packages/voluptuous/validators.py", line 215, in _run
    return self._exec(self._compiled, value, path)
  File "/srv/homeassistant-3.9.7/lib/python3.9/site-packages/voluptuous/validators.py", line 339, in _exec
    v = func(path, v)
  File "/srv/homeassistant-3.9.7/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/srv/homeassistant-3.9.7/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 386, in validate_mapping
    cval = cvalue(key_path, value)
  File "/srv/homeassistant-3.9.7/lib/python3.9/site-packages/voluptuous/validators.py", line 215, in _run
    return self._exec(self._compiled, value, path)
  File "/srv/homeassistant-3.9.7/lib/python3.9/site-packages/voluptuous/validators.py", line 339, in _exec
    v = func(path, v)
  File "/srv/homeassistant-3.9.7/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/srv/homeassistant-3.9.7/lib/python3.9/site-packages/homeassistant/helpers/config_validation.py", line 778, in validator
    if key in config:
TypeError: argument of type 'NoneType' is not iterable
2022-01-09 11:58:35 ERROR (MainThread) [homeassistant.setup] Setup failed for yandex_smart_home: Invalid config.

**Comment by dext0r** [comment]
Покажите YAML конфигурацию для компонента (если есть). Пробовали переустановить компонент через HACS?

**Comment by alting** [comment]
Нашел причину. В логах HA было:
2022-01-09 12:39:54 WARNING (MainThread) [custom_components.yandex_smart_home] The 'channel_set_via_media_content_id' option near /home/homeassistant/.homeassistant/configuration.yaml:797 is deprecated, please remove it from your configuration

Закомментировал этот параметр и интеграция сломалась. Раскомментировал обратно

**Comment by dext0r** [comment]
Скорее всего вы его неверно закоментировали, тем самым сломав yaml. Вы можете смело удалить этот параметр, на текущей версии компонента он ни на что не влияет.

**Comment by alting** [comment]
Да, удалил лишнее из конфига. Все работает! Спасибо, прошу прощения за беспокойство
