### ISSUE TITLE
Ошибка в очередности загрузки.

### ISSUE THREAD

**Issue by dmamontov** [dmitry-k/yandex_smart_home#357]
Иногда вылетает такая ошибка, когда glances запускается позже. подобная ошибка появилась с 2021.12. я вот думаю может стоить добавить отправку после старата всего hass?

```
Traceback (most recent call last):
  File "/opt/homeassistant/config/custom_components/yandex_smart_home/notifier.py", line 231, in state_change_listener
    await asyncio.gather(*[n.async_event_handler(event) for n in hass.data[DOMAIN][NOTIFIERS]])
  File "/opt/homeassistant/config/custom_components/yandex_smart_home/notifier.py", line 172, in async_event_handler
    device = yandex_entity.notification_serialize(event_entity_id)
  File "/opt/homeassistant/config/custom_components/yandex_smart_home/entity.py", line 220, in notification_serialize
    for item in [c for c in self.properties() if c.reportable]:
  File "/opt/homeassistant/config/custom_components/yandex_smart_home/entity.py", line 88, in properties
    CustomEntityProperty.get(self.hass, self.config, state, property_config)
  File "/opt/homeassistant/config/custom_components/yandex_smart_home/prop_custom.py", line 50, in get
    raise SmartHomeError(
custom_components.yandex_smart_home.error.SmartHomeError: Entity sensor.glances_cpu_thermal_1_temperature not found for temperature instance of switch.server_reboot
```

**Comment by dext0r** [comment]
В данном случае это ошибку можно игнорировать. Она не влияет на отправку статусов после того, как `sensor.glances_cpu_thermal_1_temperature` станет доступен.

В качестве костыля могу предложить создать сенсор на шаблоне, который передавать в УДЯ вместо реального сенсора:
```yaml
template:
  - sensor:
      - name: yandex_glances_cpu_thermal_1_temperature  # ну или как-то так
        unit_of_measurement: '°C'
        state: >
          {{ states('sensor.glances_cpu_thermal_1_temperature') }}
```

**Comment by dmamontov** [comment]
Как вариант. Спасибо) Сейчас просто чищу чтобы меньше было ошибок в логах)
