### ISSUE TITLE
Ошибка при запуске компонента в Home Assistant 2022.2.6

### ISSUE THREAD

**Issue by RulezzzRus** [dmitry-k/yandex_smart_home#360]
Вот такая ошибка логе:

Logger: homeassistant.loader
Source: custom_components/yandex_smart_home/capability_mode.py:328
Integration: Yandex Smart Home ([documentation](https://github.com/dmitry-k/yandex_smart_home), [issues](https://github.com/dmitry-k/yandex_smart_home/issues))
First occurred: 14:36:18 (1 occurrences)
Last logged: 14:36:18

Unexpected exception importing component custom_components.yandex_smart_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 547, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/yandex_smart_home/__init__.py", line 18, in <module>
    from . import (  # noqa: F401
  File "/config/custom_components/yandex_smart_home/capability_custom.py", line 15, in <module>
    from .capability_mode import ModeCapability
  File "/config/custom_components/yandex_smart_home/capability_mode.py", line 325, in <module>
    class ProgramCapabilityFan(ProgramCapability):
  File "/config/custom_components/yandex_smart_home/capability_mode.py", line 328, in ProgramCapabilityFan
    fan._NOT_SPEED_AUTO,
AttributeError: module 'homeassistant.components.fan' has no attribute '_NOT_SPEED_AUTO'

**Comment by dext0r** [comment]
Обновите компонент до последней версии
