### ISSUE TITLE
AttributeError: module 'homeassistant.components.media_player' has no attribute 'DEVICE_CLASS_TV'

### ISSUE THREAD

**Issue by hellad** [dmitry-k/yandex_smart_home#4]
Не подскажете на какой версии ХА должен работать этот кастомный компонент? Или как можно дальше диагностировать причину моей ошибки?
Описание возникающей ошибки:
после переноса файлов с гитхаба в папку yandex_smart_home в custom_components и добавления нескольких строк в конфиг у меня в ХА версии 0.92.2 в докере на synology даже проверка конфигурации не проходит :( . причем веб морда ХА зависает на этом и приходится перегружать контейнер средствами докера. Если же пробовать запустить, то получаю в логе следующую ошибку (про атрибут медиа плеера):

2019-05-30 00:26:05 ERROR (MainThread) [homeassistant.setup] Error during setup of component cloud

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run return loop.run_until_complete(main)

  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete

  File "/usr/src/app/homeassistant/__main__.py", line 283, in setup_and_run_hass

    log_no_color=args.log_no_color)

  File "/usr/src/app/homeassistant/bootstrap.py", line 180, in async_from_config_file

    config_dict, hass, enable_log=False, skip_pip=skip_pip)

  File "/usr/src/app/homeassistant/bootstrap.py", line 91, in async_from_config_dict

    await _async_set_up_integrations(hass, config)

  File "/usr/src/app/homeassistant/bootstrap.py", line 394, in _async_set_up_integrations

    for domain in domains_to_load

  File "/usr/src/app/homeassistant/setup.py", line 50, in async_setup_component

    return await task  # type: ignore

  File "/usr/src/app/homeassistant/setup.py", line 126, in _async_setup_component

    hass, config, integration)

  File "/usr/src/app/homeassistant/config.py", line 756, in async_process_component_config

    component = integration.get_component()

  File "/usr/src/app/homeassistant/loader.py", line 130, in get_component

    cache[self.domain] = importlib.import_module(self.pkg_path)

  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load

  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 728, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  _File "/config/custom_components/yandex_smart_home/__init__.py", line 12, in <module>

    from .const import (_

  _File "/config/custom_components/yandex_smart_home/const.py", line 73, in <module>

    (media_player.DOMAIN, media_player.DEVICE_CLASS_TV): TYPE_MEDIA_DEVICE_TV,_

**AttributeError: module 'homeassistant.components.media_player' has no attribute 'DEVICE_CLASS_TV'**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/src/app/homeassistant/setup.py", line 153, in _async_setup_component

    hass, processed_config)

  File "/usr/src/app/homeassistant/components/cloud/__init__.py", line 156, in async_setup

    await prefs.async_initialize()

  File "/usr/src/app/homeassistant/components/cloud/prefs.py", line 25, in async_initialize

    prefs = await self._store.async_load()

  File "/usr/src/app/homeassistant/helpers/storage.py", line 81, in async_load

    return await self._load_task

concurrent.futures._base.CancelledError

**Comment by dmitry-k** [comment]
DEVICE_CLASS_TV насколько я вижу появился в 0.93.0

**Comment by dmitry-k** [comment]
Добавил в README, спасибо.
