### ISSUE TITLE
Нужна помощь

### ISSUE THREAD

**Issue by fr00kt** [dmitry-k/yandex_smart_home#7]
2. @Clone this project into custom_components directory(create if required, path should look like ~/.homeassistant/custom_directory/yandex_smart_home)
Подскажите куда имиенно копиравать на Raspberry и как это дело все запустится после перезагрузки? (сори за тупые вопросы)

**Comment by dmitry-k** [comment]
https://www.home-assistant.io/docs/configuration/
В ~/.homeassistant/custom_components/yandex_smart_home
Была ошибка в README, исправил.

Это запустится только если в .configuration добавить настройку соответственно инструкции.
Custom components это стандартная фича HA: https://developers.home-assistant.io/docs/en/creating_component_loading.html

**Comment by tayanov** [comment]
Прошу прощения за офтопп. Возможно ли добавить автообновление плагина. или по вызову службы.

**Comment by Filecast** [comment]
Привет не работает mute/unmute на телеке
В логе ha: 
2019-06-06 17:18:47 ERROR (MainThread) [custom_components.yandex_smart_home.smart_home] Unexpected error
Traceback (most recent call last):
  File "/home/den/.homeassistant/custom_components/yandex_smart_home/smart_home.py", line 48, in _process
    result = await handler(hass, data, message)
  File "/home/den/.homeassistant/custom_components/yandex_smart_home/smart_home.py", line 178, in handle_devices_execute
    capability.get('state', {}))
  File "/home/den/.homeassistant/custom_components/yandex_smart_home/helpers.py", line 174, in execute
    if type == cpb.type and state['instance'] == cpb.instance:
TypeError: 'NoneType' object is not subscriptable
2019-06-06 17:18:47 ERROR (MainThread) [custom_components.yandex_smart_home.smart_home] Error handling message {'payload': {'devices': [{'id': 'media_player.lg_tv', 'capabilities': [{'type': 'devices.capabilities.toggle', 'state': None}]}, {'id': 'media_player.living_room_tv', 'capabilities': [{'type': 'devices.capabilities.toggle', 'state': None}]}]}}: {'error_code': 'INTERNAL_ERROR'}
2019-06-06 17:19:01 ERROR (MainThread) [custom_components.yandex_smart_home.smart_home] Unexpected error
Traceback (most recent call last):
  File "/home/den/.homeassistant/custom_components/yandex_smart_home/smart_home.py", line 48, in _process
    result = await handler(hass, data, message)
  File "/home/den/.homeassistant/custom_components/yandex_smart_home/smart_home.py", line 178, in handle_devices_execute
    capability.get('state', {}))
  File "/home/den/.homeassistant/custom_components/yandex_smart_home/helpers.py", line 174, in execute
    if type == cpb.type and state['instance'] == cpb.instance:
TypeError: 'NoneType' object is not subscriptable
2019-06-06 17:19:01 ERROR (MainThread) [custom_components.yandex_smart_home.smart_home] Error handling message {'payload': {'devices': [{'id': 'media_player.lg_tv', 'capabilities': [{'type': 'devices.capabilities.toggle', 'state': None}]}, {'id': 'media_player.living_room_tv', 'capabilities': [{'type': 'devices.capabilities.toggle', 'state': None}]}]}}: {'error_code': 'INTERNAL_ERROR'}

**Comment by dmitry-k** [comment]
> Прошу прощения за офтопп. Возможно ли добавить автообновление плагина. или по вызову службы.

К сожалению я не знаю нормального способа за исключением написания скрипта.

> Привет не работает mute/unmute на телеке

Выглядит очень странно. Может быть временные проблемы у яндекса и неправильный запрос в результате.
Если проблема не исчезла, пожалуйста создайте отдельный issue, попробуем разобраться.
