### ISSUE TITLE
Не добавляются устройства

### ISSUE THREAD

**Issue by alexpod93** [dmitry-k/yandex_smart_home#82]
У меня довольно странная ошибка образовалась.
Если просто добавить устройства через 
```
  filter:
    include_entities:
     - light.zal
```
то устройства прекрасно добавляются.

Если добавить entity_config
```
  filter:
    include_entities:
     - light.zal
  entity_config:
    light.zal:
      name: Свет в зале
      room: Гостиная
```
то яндекс уже не может обновить устройства.
Пробовал латиницу брать в кавычки - не помогло.
Руками прописал все комнаты в приложении - не помогло.
В чем может быть проблема?

**Comment by KKnishev** [comment]
у меня в конфиге описания прописаны так:
```
entity_config:
  light.zal:
    name: 'Свет в зале'
    room: 'Гостиная'
```

но устройства тоже перестали обновляться: Произошла ошибка, попробуйте позже. Если ошибка продолжает возникать, поищите решение проблемы на странице помощи.
Старые работают, созданные пару месяцев назад, хотел добавить новых и нифига, правда я на форке @alryaz, но не думаю что в этом проблема...

**Comment by KKnishev** [comment]
в логе при запросе обновления только INTERNAL_ERROR :(

```
2020-06-25 15:30:55 ERROR (MainThread) [custom_components.yandex_smart_home.core.smart_home] Unexpected error
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/core/smart_home.py", line 46, in _process
    result = await handler(hass, data, message)
  File "/config/custom_components/yandex_smart_home/core/smart_home.py", line 94, in async_devices_sync
    serialized = await entity.devices_serialize()
  File "/config/custom_components/yandex_smart_home/core/helpers.py", line 172, in devices_serialize
    description = cpb.description()
  File "/config/custom_components/yandex_smart_home/functions/capability.py", line 110, in description
    parameters = self.parameters()
  File "/config/custom_components/yandex_smart_home/functions/capability.py", line 131, in parameters
    return self.parameters_default()
  File "/config/custom_components/yandex_smart_home/functions/capability.py", line 635, in parameters_default
    for v in custom_values.keys()
AttributeError: 'bool' object has no attribute 'keys'
2020-06-25 15:30:55 ERROR (MainThread) [custom_components.yandex_smart_home.core.smart_home] Error handling message {}: {'error_code': 'INTERNAL_ERROR'}
```

**Comment by dmitry-k** [comment]
По оригинальной ошибке ничего не скажу. Нужны хоть какие-то логи.
Ошибка из последнего сообщения явно связана с форком. Такого кода здесь нет.

**Comment by KKnishev** [comment]
Дмитрий, спасибо за ответ, понятно что немного не по адресу, но почему-то у @alryaz раздел issues закрыт на проекте, некуда писать  ;)

**Comment by alryaz** [comment]
@KKnishev открыл issues, буду смотреть

**Comment by dmak** [comment]
> но устройства тоже перестали обновляться: Произошла ошибка, попробуйте позже. Если ошибка продолжает возникать, поищите решение проблемы на странице помощи.

У меня похожая, если не точно такая же, проблема. На шаге, где в мобильном приложении надо нажать "Обновить список устройств", возникает непонятная ошибка (см. скриншот). В HASS логах вижу только:
```
2020-06-29 02:32:16 DEBUG (MainThread) [homeassistant.components.http.auth] Authenticated 37.9.68.172 for /yandex_smart_home/v1.0/user/devices using bearer token
```
Никак ошибок нет, ровно, как и других сообщений, связанных с Yandex. У меня работает интеграция в Google Home, поэтому полагаю, что с доменом и SSL сертификатами всё в порядке. Где можно дополнительно что-то посмотреть?

<img src="https://sprut.ai/static/media/cache/00/56/90/5/4241012/61604/1000x_image.jpg" width="400">

**Comment by dmitry-k** [comment]
В яндексе есть вкладка тестирование, там можно посмотреть запросы и ответы. Для компоненте можно включить [дебаг лог](https://www.home-assistant.io/integrations/logger/) и тоже смотреть запросы/ответы.

**Comment by dmak** [comment]
Спасибо за подсказку! В HomeAssistant прописал настройки логгинга (забыл упомянуть, что интеграция у меня одной лаконичной строчкой включена):
```
logger:                                         
  logs:                                         
     custom_components.yandex_smart_home: debug

yandex_smart_home:
```
Зашёл на вкладку "Тестирование", потом "Опубликованная версия", нажал "+", выбрал "Другое устройство", залогинился в свой HomeAssistant с помощью пароля, нажал "Обновить список устройств" и та же ошибка, причём лог запросов пуст:
![image](https://user-images.githubusercontent.com/366965/86106062-663d4500-bac0-11ea-8235-7c1f9afcef40.png)
Как минимум что-то должно быть в окошке, связанное с авторизацией. Я в недоумении.

В логе HomeAssistant ничего дополнительного не появилось. На самом деле я не удивлён: у меня не было ограничений для этой компоненты. Если искать по слову `yandex`, то вот, в целом, весь лог от старта HomeAssistant:
```
2020-06-30 10:53:58 INFO (MainThread) [homeassistant.setup] Setting up yandex_smart_home                                                    
2020-06-30 10:53:58 INFO (MainThread) [homeassistant.setup] Setup of domain yandex_smart_home took 0.1 seconds.                             
2020-06-30 10:54:05 DEBUG (SyncWorker_34) [homeassistant.util.json] JSON file not found: /var/lib/homeassistant/.homeassistant/custom_components/yandex_smart_home/translations/en.json
2020-06-30 10:56:06 DEBUG (MainThread) [homeassistant.components.http.auth] Authenticated 37.9.87.105 for /yandex_smart_home/v1.0/user/devices using bearer token
```

**Comment by dmitry-k** [comment]
"translations/en.json" тут нет. Если есть возможность, попробуйте поставить не форк, а версию отсюда.

**Comment by dmak** [comment]
Не совсем понятно, какую именно версию вы имели в виду. Тем не менее, я взял версию [отсюда](https://github.com/alryaz/hass-component-yandex-smart-home) (после клонирования откатил на v2.0.3 по инструкции). В результате то же самое в логах, и такой же результат (неизвестная ошибка). Буду признателен за пример лога при обновлении устройств.

**Comment by dmitry-k** [comment]
А, извиняюсь, я ошибся. Показалось что вы используете другую версию.

Особого смысла в примере лога не виже, что-то типа:

> 2020-07-01 11:54:48 DEBUG (MainThread) [custom_components.yandex_smart_home.http] Request: https://xxx/api/yandex_smart_home/v1.0/user/devices
> 2020-07-01 11:54:48 DEBUG (MainThread) [custom_components.yandex_smart_home.http] Response: {'request_id': '871fb025-8219-4248-aa67-e50dfcd00752', 'payload': {'user_id': '...', 'devices': [{'id': 'input_boolean.pause', 'name': 'Пауза', 'type': 'devices.types.switch', 'capabilities': [{'type': 'devices.capabilities.on_off', 'retrievable': True}]...}]}}

Судя по всему ваши запросы не доходят до home assistant. У вас SSL настроен? Home assistant точно доступен из внешнего интернета?

**Comment by dmak** [comment]
Очень извиняюсь за ложное сообщение об ошибке. Нашёл проблему в конфигурации умного дома в Yandex: вместо URL `https://.../api/yandex_smart_home` указал `https://.../yandex_smart_home`, то есть, пропустил `/api`, поэтому после авторизации запросы не приходили. После фикса, лог такой:
```
2020-07-01 09:30:44 DEBUG (MainThread) [homeassistant.components.http.auth] Authenticated 5.45.235.114 for /api/yandex_smart_home/v1.0/user/devices using bearer token
2020-07-01 09:30:44 DEBUG (MainThread) [custom_components.yandex_smart_home.core.http] Request: http://localhost:8123/api/yandex_smart_home/v1.0/user/devices
...
2020-07-01 09:30:44 DEBUG (MainThread) [custom_components.yandex_smart_home.core.smart_home] No mapping for <state zone.home=zoning; hidden=True, latitude=52.03616507434834, longitude=4.358890056610108, radius=100, passive=False, editable=True, friendly_name=Home, icon=mdi:home @ 2020-06-30T21:01:08.126026+02:00> domain
2020-07-01 09:30:44 ERROR (MainThread) [custom_components.yandex_smart_home.core.smart_home] Unexpected error
Traceback (most recent call last):
  File "/var/lib/homeassistant/.homeassistant/custom_components/yandex_smart_home/core/smart_home.py", line 46, in _process
    result = await handler(hass, data, message)
  File "/var/lib/homeassistant/.homeassistant/custom_components/yandex_smart_home/core/smart_home.py", line 94, in async_devices_sync
    serialized = await entity.devices_serialize()
  File "/var/lib/homeassistant/.homeassistant/custom_components/yandex_smart_home/core/helpers.py", line 172, in devices_serialize
    description = cpb.description()
  File "/var/lib/homeassistant/.homeassistant/custom_components/yandex_smart_home/functions/capability.py", line 110, in description
    parameters = self.parameters()
  File "/var/lib/homeassistant/.homeassistant/custom_components/yandex_smart_home/functions/capability.py", line 130, in parameters
    return self.parameters_default()
  File "/var/lib/homeassistant/.homeassistant/custom_components/yandex_smart_home/functions/capability.py", line 651, in parameters_default
    for v in custom_numeric_modes.keys()
AttributeError: 'NoneType' object has no attribute 'keys'
2020-07-01 09:30:44 ERROR (MainThread) [custom_components.yandex_smart_home.core.smart_home] Error handling message {}: {'error_code': 'INTERNAL_ERROR'}
```
То есть, ошибка на экране мобильного приложения та же, но кухня под капотом другая.

Версия HomeAssistant: 0.111.4

**Comment by Lisenok425** [comment]
Всем добрый день Такая-же проблема вроде все проверил все норм но устройств нет, раньше все работало.

**Comment by 4sag** [comment]
Авторизация проходит, но при обновлении устройств (Произошла ошибка, попробуйте позже. Если ошибка продолжает возникать, поищите решение проблемы на странице помощи)

ERROR (MainThread) [custom_components.yandex_smart_home.core.smart_home] Unexpected error
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/core/smart_home.py", line 46, in _process
    result = await handler(hass, data, message)
  File "/config/custom_components/yandex_smart_home/core/smart_home.py", line 94, in async_devices_sync
    serialized = await entity.devices_serialize()
  File "/config/custom_components/yandex_smart_home/core/helpers.py", line 172, in devices_serialize
    description = cpb.description()
  File "/config/custom_components/yandex_smart_home/functions/capability.py", line 110, in description
    parameters = self.parameters()
  File "/config/custom_components/yandex_smart_home/functions/capability.py", line 130, in parameters
    return self.parameters_default()
  File "/config/custom_components/yandex_smart_home/functions/capability.py", line 651, in parameters_default
    for v in custom_numeric_modes.keys()

**Comment by dmitry-k** [comment]
@4sag, @dmak  ваши лог похоже для форка https://github.com/alryaz/hass-component-yandex-smart-home судя по всему, рекомендую создать issue там.

**Comment by dmak** [comment]
@dmitry-k Предлагаю вам тогда выводить в лог версию компоненты с каким-то суффиксом (хеш коммита?), чтобы можно было понять, что за компонента используется. В том, что работает компонента именно из этого репозитория у меня нету сомнений – она одна у меня.
Я обновил компоненту до последней версии в master, и устройства пробросились. Не знаю, как это объяснить. Звёзды сошлись.

**Comment by dmitry-k** [comment]
У вас в логе чётко виден путь /custom_components/yandex_smart_home/core/smart_home.py
У меня в репозитории нет каталога "core" и никогда не было. Тоже самое с каталагом "functions". Вы что-то откуда-то не отсюда поставили. Это не звёзды, предлагаю быть внимательнее. Хэш коммита не поможет - никто всё-равно смотреть не будет, да и технически это не всегда возможно.
