### ISSUE TITLE
Проблемы работы за reverse proxy

### ISSUE THREAD

**Issue by alive-corpse** [dmitry-k/yandex_smart_home#86]
Добрый день. Спасибо большое за вашу работу!

HA: 0.110.4
Python: 3.7.3 (virtualenv)
yandex_smart_home: склонировал три дня назад

Есть полтора десятка различных сервисов, перед которыми стоит nginx c let's encrypt сертификатом. Все остальные сервисы работают нормально, при попытке связать HA, который бежит за тем же nginx с яндексом выдает "Произошла ошибка в процессе получения данных от сервиса". HA в дебаг логе выдаёт ошибку авторизации. При этом с тем же логином и паролем, вставленными из буфера обмена я без проблем авторизуюсь снаружи браузером, урлы доступны (что так же можно видеть по логу, приведённому ниже). Если добавить в http пути к сертификатам и выставить порт HA наружу, то всё работает, но HA при этом неистово заваливает лог ошибками вида:
```
2020-07-26 04:15:07 ERROR (MainThread) [homeassistant.core] Error doing job: SSL handshake failed
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:1056)
2020-07-26 04:15:07 ERROR (MainThread) [homeassistant.core] Error doing job: SSL error in data received
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:1056)
```
Решения этой проблемы вроде пока нет, кроме отката на предыдущие версии (на которых у меня не работает кое-что из интеграций), поэтому хотелось сделать именно проксипассом. Да и чтобы отдельно не менять сертификаты в нескольких местах.

В логах nginx при попытке связать аккаунт, появляется следующее (получение статики вырезал, порт и урл изменены):

```
"GET /auth/authorize?state=https%3A%2F%2Fsocial.yandex.ru%2Fbroker2%2Fauthz_in_app%2F20f3e29f79964e2cb7e4e2a26ef75689%2Fcallback&redirect_uri=https%3A%2F%2Fsocial.yandex.net%2Fbroker%2Fredirect&response_type=code&client_id=https%3A%2F%2Fsocial.yandex.net%2F HTTP/2.0" 200 2037 "-" 
"GET /frontend_latest/authorize.773e20bb.js HTTP/2.0" 200 117797 "https://ha.my.domain:myport/auth/authorize?state=https%3A%2F%2Fsocial.yandex.ru%2Fbroker2%2Fauthz_in_app%2F20f3e29f79964e2cb7e4e2a26ef75689%2Fcallback&redirect_uri=https%3A%2F%2Fsocial.yandex.net%2Fbroker%2Fredirect&response_type=code&client_id=https%3A%2F%2Fsocial.yandex.net%2F" 
"GET /frontend_latest/chunk.71b853fc3306a110f8e6.js HTTP/2.0" 200 1384 "https://ha.my.domain:myport/auth/authorize?state=https%3A%2F%2Fsocial.yandex.ru%2Fbroker2%2Fauthz_in_app%2F20f3e29f79964e2cb7e4e2a26ef75689%2Fcallback&redirect_uri=https%3A%2F%2Fsocial.yandex.net%2Fbroker%2Fredirect&response_type=code&client_id=https%3A%2F%2Fsocial.yandex.net%2F" 
"GET /frontend_latest/chunk.fdee1fc23352878fb1be.js HTTP/2.0" 200 3282 "https://ha.my.domain:myport/auth/authorize?state=https%3A%2F%2Fsocial.yandex.ru%2Fbroker2%2Fauthz_in_app%2F20f3e29f79964e2cb7e4e2a26ef75689%2Fcallback&redirect_uri=https%3A%2F%2Fsocial.yandex.net%2Fbroker%2Fredirect&response_type=code&client_id=https%3A%2F%2Fsocial.yandex.net%2F" 
"GET /auth/providers HTTP/2.0" 200 60 "https://ha.my.domain:myport/auth/authorize?state=https%3A%2F%2Fsocial.yandex.ru%2Fbroker2%2Fauthz_in_app%2F20f3e29f79964e2cb7e4e2a26ef75689%2Fcallback&redirect_uri=https%3A%2F%2Fsocial.yandex.net%2Fbroker%2Fredirect&response_type=code&client_id=https%3A%2F%2Fsocial.yandex.net%2F" 
"POST /auth/login_flow HTTP/2.0" 200 172 "https://ha.my.domain:myport/auth/authorize?state=https%3A%2F%2Fsocial.yandex.ru%2Fbroker2%2Fauthz_in_app%2F20f3e29f79964e2cb7e4e2a26ef75689%2Fcallback&redirect_uri=https%3A%2F%2Fsocial.yandex.net%2Fbroker%2Fredirect&response_type=code&client_id=https%3A%2F%2Fsocial.yandex.net%2F" 
"GET /manifest.json HTTP/2.0" 200 883 "https://ha.my.domain:myport/auth/authorize?state=https%3A%2F%2Fsocial.yandex.ru%2Fbroker2%2Fauthz_in_app%2F20f3e29f79964e2cb7e4e2a26ef75689%2Fcallback&redirect_uri=https%3A%2F%2Fsocial.yandex.net%2Fbroker%2Fredirect&response_type=code&client_id=https%3A%2F%2Fsocial.yandex.net%2F" 
"GET /frontend_latest/chunk.35951da26b088b8802bb.js HTTP/2.0" 200 14150 "https://ha.my.domain:myport/auth/authorize?state=https%3A%2F%2Fsocial.yandex.ru%2Fbroker2%2Fauthz_in_app%2F20f3e29f79964e2cb7e4e2a26ef75689%2Fcallback&redirect_uri=https%3A%2F%2Fsocial.yandex.net%2Fbroker%2Fredirect&response_type=code&client_id=https%3A%2F%2Fsocial.yandex.net%2F" 
"POST /auth/login_flow/bbdbb8a156ff415ebc7046e385da831b HTTP/2.0" 200 180 "https://ha.my.domain:myport/auth/authorize?state=https%3A%2F%2Fsocial.yandex.ru%2Fbroker2%2Fauthz_in_app%2F20f3e29f79964e2cb7e4e2a26ef75689%2Fcallback&redirect_uri=https%3A%2F%2Fsocial.yandex.net%2Fbroker%2Fredirect&response_type=code&client_id=https%3A%2F%2Fsocial.yandex.net%2F"
```

Вот конфиг nginx для виртуалхоста HA:
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {                                             
    listen 443 ssl http2;
    server_name my.domain;

    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";

    # пути к сертификату и ключу прописаны в default.conf, поэтому тут их нет

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;

    error_log  /var/www/my.domain/logs/error.log;
    access_log /var/www/my.domain/logs/access.log;

    proxy_buffering off;

    location / {
      proxy_set_header X-Forwarded-Proto "https";
      proxy_pass http://10.11.11.2:8123;
      proxy_buffering off;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
    }

}
```

Чего-то особого не хватает в конфиге?

**Comment by pervolianinen** [comment]
А на каких версиях у вас отрабатывает?

**Comment by pervolianinen** [comment]
> Решения этой проблемы вроде пока нет, кроме отката на предыдущие версии (на которых у меня не работает кое-что из интеграций), 

А на каких версиях у вас отрабатывает?

**Comment by nick2525** [comment]
Поставь haproxy

**Comment by prokudin0777** [comment]
Нарыл тут, что надо отключить IPV6
Надо отключить не сам ipv6, а сделать так, что бы на запрос вашего доменного имени с HA, dns сервер выдавал адрес в формате ipv4. Сделать это проще в админке вашего регистратора или хостера. Необходимо отредактировать записи зоны вашего днс имени, просто сотрите запись АААА.

[https://kvvhost.ru/2019/05/31/home-assistant-alice/](url). - ищите в комментах
