### ISSUE TITLE
Крашик с румбой

### ISSUE THREAD

**Issue by ixkor** [dmitry-k/yandex_smart_home#95]
С последним апдейтом кажется что то сломалось с обработкой пылесосов:
```
2020-09-15 13:04:26 ERROR (MainThread) [custom_components.yandex_smart_home.smart_home] Unexpected error
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/smart_home.py", line 46, in _process
    result = await handler(hass, data, message)
  File "/config/custom_components/yandex_smart_home/smart_home.py", line 118, in async_devices_query
    devices.append(entity.query_serialize())
  File "/config/custom_components/yandex_smart_home/helpers.py", line 197, in query_serialize
    capabilities.append(cpb.get_state())
  File "/config/custom_components/yandex_smart_home/capability.py", line 95, in get_state
    'value': self.get_value()
  File "/config/custom_components/yandex_smart_home/capability.py", line 1093, in get_value
    return self.parameters()['modes'][0]['value']
IndexError: list index out of range
```
По крайней мере у моего iRobot Roomba такая вот ошибка. И список устройств обновить не могу из за неё.

**Comment by ixkor** [comment]
@dmitry-k, спасибо за фикс, но ты кажется в коммите с фиксом потерял `['value']`
